config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    resources :projects
  end

  root to: 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  has_many :projects
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

   def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_out_path_for(user)
    user_session_path
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :find_user, except: :index

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = @user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to [@user, @project], notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to [@user, @project], notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to user_projects_url(@user), notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end

    def find_user
      @user = User.find(params[:user_id])
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RubyGarageProjects" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">RubyGarageProjects</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li>  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
            <% else %>
              <li><%= link_to('Login', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Ruby Garage 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for [@user, @project], html: { class: "form-horizontal project" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, class: 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to 'Cancel', user_projects_path(current_user), class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit project</h1>
</div>
<%= render partial: 'form' %>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>Projects</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Author</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, user_project_path(project.user, project) %></td>
        <td><%= project.description %></td>
        <td><%= project.user.name %></td>
        <td>
          <%= link_to 'Edit', edit_user_project_path(project.user, project), class: 'btn btn-default btn-xs' %>
          <%= link_to 'Destroy', user_project_path(project.user, project), method: :delete,
                      data: { confirm:  'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_user_project_path(current_user), class: 'btn btn-primary' if current_user %>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>New project</h1>
</div>
<%= render partial: 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <h1>Project</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @project.name %></dd>
  <dt><strong>Description:</strong></dt>
  <dd><%= @project.description %></dd>
  <dt><strong>Author:</strong></dt>
  <dd><%= @project.user.name %></dd>
</dl>

<%= link_to 'Back', user_projects_path(current_user), class: 'btn btn-default' %>
<%= link_to 'Edit', edit_user_project_path(current_user, @project), class: 'btn btn-default' %>
<%= link_to 'Destroy', user_project_path(current_user, @project), method: 'delete', confirm:  'Are you sure?', class: 'btn btn-danger' %>